In [3]:
import pandas as pd
import re
#set ups
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
# importing package 
import matplotlib.pyplot as plt 
import numpy as np 
import requests

#setups
%matplotlib inline

In [4]:
df=pd.read_csv("listings_full.csv")

## Ελέγχουμε το df

In [5]:
df.shape

(13182, 75)

In [6]:
df.dtypes

id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
name                                             object
description                                     float64
neighborhood_overview                            object
picture_url                                      object
host_id                                           int64
host_url                                         object
host_name                                        object
host_since                                       object
host_location                                    object
host_about                                       object
host_response_time                               object
host_response_rate                               object
host_acceptance_rate                             object
host_is_superhost                                object
host_thumbnail_url                               object
host_picture_url                                 object
host_neighbourhood                               object
host_listings_count                               int64
host_total_listings_count                         int64
host_verifications                               object
host_has_profile_pic                             object
host_identity_verified                           object
neighbourhood                                    object
neighbourhood_cleansed                           object
neighbourhood_group_cleansed                    float64
latitude                                        float64
longitude                                       float64
property_type                                    object
room_type                                        object
accommodates                                      int64
bathrooms                                       float64
bathrooms_text                                   object
bedrooms                                        float64
beds                                            float64
amenities                                        object
price                                            object
minimum_nights                                    int64
maximum_nights                                    int64
minimum_minimum_nights                            int64
maximum_minimum_nights                            int64
minimum_maximum_nights                            int64
maximum_maximum_nights                            int64
minimum_nights_avg_ntm                          float64
maximum_nights_avg_ntm                          float64
calendar_updated                                float64
has_availability                                 object
availability_30                                   int64
availability_60                                   int64
availability_90                                   int64
availability_365                                  int64
calendar_last_scraped                            object
number_of_reviews                                 int64
number_of_reviews_ltm                             int64
number_of_reviews_l30d                            int64
first_review                                     object
last_review                                      object
review_scores_rating                            float64
review_scores_accuracy                          float64
review_scores_cleanliness                       float64
review_scores_checkin                           float64
review_scores_communication                     float64
review_scores_location                          float64
review_scores_value                             float64
license                                          object
instant_bookable                                 object
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
dtype: object

In [32]:
# κρατάω τις στήλες που αφορουν΄ την ανάλυση
df=df[['id',
       'name', 
       'host_id',
       'host_name', 
       'host_since',
       'host_location', 
       'host_is_superhost',
       'host_neighbourhood', 
       'host_listings_count',
       'host_total_listings_count',
       'neighbourhood',
       'neighbourhood_cleansed',
       'latitude', 'longitude',
       'property_type',
       'room_type',
       'bathrooms_text',
       'beds',
       'price',
       'minimum_nights', 
       'maximum_nights',
       'minimum_minimum_nights',
       'maximum_minimum_nights',
       'minimum_maximum_nights',
       'maximum_maximum_nights',
       'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 
       'availability_365', 
       'review_scores_rating',
       'review_scores_accuracy',
       'license',
       'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms']].copy()

In [33]:
df.describe()

,id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,beds,minimum_nights,maximum_nights,minimum_minimum_nights,maximum_minimum_nights,minimum_maximum_nights,maximum_maximum_nights,minimum_nights_avg_ntm,maximum_nights_avg_ntm,availability_365,review_scores_rating,review_scores_accuracy,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms
count,1.318200e+04,1.318200e+04,13182.000000,13182.000000,13182.000000,13182.000000,13017.000000,13182.000000,13182.000000,13182.000000,13182.000000,13182.000000,13182.000000,13182.000000,13182.000000,13182.000000,11075.000000,11075.000000,13182.000000,13182.000000,13182.000000,13182.000000
mean,3.954590e+17,2.166796e+08,20.644895,32.083447,37.980172,23.731728,2.071368,3.151267,571.466925,3.197390,4.595812,757.426567,781.464421,4.157988,767.141405,222.418146,4.737552,4.783382,12.034441,10.849416,1.031027,0.071082
std,4.270628e+17,1.732957e+08,61.423587,136.062916,0.013427,0.012480,1.412656,16.231489,457.941252,18.416376,26.587753,449.324853,437.633288,24.276247,440.906213,136.667965,0.431216,0.394101,19.431829,18.978576,4.439618,0.850407
min,1.059500e+04,1.805000e+03,1.000000,1.000000,37.950322,23.697700,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,3.166800e+07,6.022029e+07,1.000000,2.000000,37.969140,23.723970,1.000000,1.000000,90.000000,1.000000,1.000000,365.000000,365.000000,1.000000,365.000000,88.000000,4.680000,4.750000,1.000000,1.000000,0.000000,0.000000
50%,5.312285e+07,1.821563e+08,5.000000,6.000000,37.978573,23.729719,2.000000,2.000000,365.000000,2.000000,2.000000,1125.000000,1125.000000,2.000000,1125.000000,268.000000,4.860000,4.890000,4.000000,3.000000,0.000000,0.000000
75%,8.516889e+17,3.696750e+08,20.000000,23.000000,37.988298,23.737657,3.000000,2.000000,1125.000000,2.000000,3.000000,1125.000000,1125.000000,2.300000,1125.000000,348.000000,4.980000,5.000000,14.000000,12.000000,0.000000,0.000000
max,1.052831e+18,5.516695e+08,2444.000000,5529.000000,38.030830,23.780220,30.000000,800.000000,4444.000000,800.000000,1000.000000,4444.000000,4444.000000,800.000000,4444.000000,365.000000,5.000000,5.000000,121.000000,121.000000,44.000000,15.000000

In [34]:
# Ποιος είναι ο πιο συνηθισμένος τύπος δωματίου που συναντάμε στην πλατφρόμα;
df['room_type'].value_counts(normalize=True)*100

room_type
Entire home/apt    90.320134
Private room        8.276438
Hotel room          0.773782
Shared room         0.629646
Name: proportion, dtype: float64

### Πόσοι host έχουν πάνω από δύο καταχωρήσεις;

In [35]:
# κρατάμε τα ολόκληρα καταλύματα, καθώς αυτά συναντάμε συχνότερα
ent_house=df[df.room_type.str.contains('Entire',case=False)].copy().reset_index()
# βρίσκω πόσα entire homes έχει ο κάθε host 
listing = pd.DataFrame(ent_house.host_id.value_counts(ascending=False)).copy().reset_index()

In [36]:
# κατηγοριοποιώ πόσα ακίνητα έχει ο κάθε host (οικοδεσπότης)
# με βάση την ελληνική νομοθεσία, από 3 και πάνω, η κατηγοριοποίηση αλλάζει
# αν έχουν πάνω από 3: 1
# αν έχουν κάτω από 3: 0
listing['many_properties']= listing['count'].apply(lambda x: 1 if x>2 else 0)

### Σε ποιές περιοχές έχουν περισσότερες καταχωρήσεις(listings);

In [37]:
# κρατάμε μόνο τις τιμές που είναι αληθείς 
# και τις χρησιμοποιούμε για τον εντοπισμό των host στο γενικό σύνολο δεδομένων
list_business_hosts = listing[listing['many_properties']>0].host_id.tolist()

In [38]:
# περνάς τη νέα μεταβλητή στο df σου
ent_house['many_properties'] = ent_house['host_id'].apply(lambda x: 1 if x in list_business_hosts else 0)

In [39]:
# Ποιο είναι το ποσοστό των κατοικιών που ανήκουν σε επαγγελματίες οικοδεσπότες ;
kat_prof=ent_house["many_properties"].value_counts(normalize=True)*100

### Καθαρίζουμε τις τιμές

In [40]:
from money_parser import price_str
from decimal import Decimal

In [41]:
def correct_prices(dirty_price):
    if not pd.isna(dirty_price): 
        amount_num = price_str(dirty_price) 
        amount_decimal = Decimal(str(amount_num)) 
        return float(amount_decimal)

In [42]:
ent_house['cleaned_price'] = ent_house['price'].apply(lambda x: correct_prices(x))

### Mέση τιμή ανά διανυκτέρευση

In [43]:
# Για κάθε περιοχή ξεχωριστά

# ομαδοποίηση με βάση τις στήλες 'neighborhood_cleansed', 'many_properties' 
# και εφαρμόζουμε συγκεντρωτικά τις του μέσου όρου και της διάμεσου στις τιμές που καθαρίσαμε.
price_per_night_area=ent_house.groupby(by=['neighbourhood_cleansed', 'many_properties'])['cleaned_price'].agg(['median', 'mean']).reset_index()

In [44]:
# Για όλη την Αθήνα
price_per_night=ent_house.groupby(by=['many_properties'])['cleaned_price'].agg(['median', 'mean']).reset_index()

### Υπάρχει διαφορά τιμών μεταξύ  των διαμερισμάτων των εππαγελματιών και των ερασιτεχνών;

In [45]:
# κρατάμε το median των τιμών ανά περιοχή
price_per_night_area_med= price_per_night_area[['neighbourhood_cleansed','many_properties','median']].reset_index(drop=True).copy()

In [46]:
# ξαναστείνουμε το df ώστε να έχουμε σε μία στηλη τις τιμές όσων έχουν λιγότερα από 3 διαμερίσματα 
# και σε μία άλλη όσων εχουν περισσότερα
pay_comp=price_per_night_area_med.pivot_table(values='median', index='neighbourhood_cleansed', columns='many_properties').reset_index().copy()
pay_comp=pay_comp.rename(columns={0:'less_than_3', 
                                  1:'more_than_3'})

In [47]:
# βρίσκουμε τη διαφορά των τιμών ανά περιοχή 
# και στήνουμε το df ώστε να φαίνονται πρώτες οι περιοχές με τη μεγαλύτερη διαφορά
pay_comp['price_difference']= (pay_comp.more_than_3 - pay_comp.less_than_3 )
pay_comp = pay_comp.sort_values(by='price_difference', ascending=False).reset_index(drop=True).copy()

### Σε πόσες περιοχές τα διαμέρίσματα που ανήκουν σε επαγγελματίες οικοδεσπότες είναι πιο ακριβά;

In [48]:
#ξεχωρίζουμε τις διαφορές στις περιοχές που υπάρχει διαφορά 
# αν η διαφορά είναι πάνω από το 0, η τιμή των διαμερισμάτων των επαγγελματιών είναι υψηλότερη
# αν η διαφορά είναι πάνω από το 0, η τιμή των διαμερισμάτων των ερασιτεχνών είναι υψηλότερη 
#  αν δεν υπάρχει διαφορά δεν λαμβάνεται υπόψη
more=[]
less=[]

for i, item in pay_comp.iterrows():
    if item['price_difference'] > 0:
        more.append(item['neighbourhood_cleansed'])
    elif item['price_difference'] < 0:
        less.append(item['neighbourhood_cleansed'])

In [49]:
#  βρίσκουμε την διαφορά για κάθε περιοχή
pay_comp['percentage_difference'] = ((pay_comp['more_than_3'] - pay_comp['less_than_3']) / ((pay_comp['more_than_3'] + pay_comp['less_than_3']) / 2)) * 100
pay_comp=pay_comp.sort_values(by='percentage_difference', ascending=False)

# Ερωτήσεις

### 1) Πόσοι host έχουν πάνω από δύο καταχωρήσεις;

In [50]:
how_many_porperties= listing['many_properties'].value_counts(normalize=True)*100\

text= f' Στην πλατφόρμα του Airbnb, to {round(how_many_porperties[1])} των host(οικοδεσποτών) έχουν περισσότερα από 2 ακίνητα.'
text

' Στην πλατφόρμα του Airbnb, to 14 των host(οικοδεσποτών) έχουν περισσότερα από 2 ακίνητα.'

### 2) Πόσες καταχωρήσεις ανήκουν σε αυτούς τους host;

In [51]:
kat_prof=ent_house["many_properties"].value_counts(normalize=True)*100

In [52]:
owned_by_prof=kat_prof[1]
owned_by_amateurs=kat_prof[0]

text= f'Από τις κατοικίες που έχουν καταχωρηθεί στην πλατφόρμα, το {round(owned_by_prof)}% ανήκει σε επαγγελματίες οικοδεσπότες \
ένω το {round(owned_by_amateurs)}% ανήκει σε οικοδεσπότες χωρίς επαγγελματική δραστηριότητα.'

text

'Από τις κατοικίες που έχουν καταχωρηθεί στην πλατφόρμα, το 54% ανήκει σε επαγγελματίες οικοδεσπότες ένω το 46% ανήκει σε οικοδεσπότες χωρίς επαγγελματική δραστηριότητα.'

In [53]:
### Ποιο είναι το ποσοστό των κατοικιών που ανήκουν σε επαγγελματίες οικοδεσπότες ;

### 3) Ποιές είναι οι περιοχές με το μεγαλύτερο ποσοστό τέτοιου είδους καταχωρήσεων;

In [54]:
ent_house['neighbourhood_cleansed'].value_counts(normalize=True)*100

neighbourhood_cleansed
ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ              17.772552
ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ                  8.945070
ΝΕΟΣ ΚΟΣΜΟΣ                          7.878381
ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ             7.492021
ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ     5.954981
ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ                      4.342348
ΠΑΓΚΡΑΤΙ                             4.233160
ΑΜΠΕΛΟΚΗΠΟΙ                          3.586427
ΚΟΛΩΝΑΚΙ                             3.309256
ΑΚΡΟΠΟΛΗ                             3.099278
ΠΕΤΡΑΛΩΝΑ                            2.998488
ΘΗΣΕΙΟ                               2.880900
ΚΕΡΑΜΕΙΚΟΣ                           2.628927
ΚΥΨΕΛΗ                               2.024189
ΣΤΑΔΙΟ                               1.931799
ΓΟΥΔΙ                                1.839409
ΙΛΙΣΙΑ                               1.705023
ΖΑΠΠΕΙΟ                              1.411053
ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ                     1.343860
ΝΙΡΒΑΝΑ                              1.285066
ΛΥΚΑΒΗΤΤΟΣ                           1.285066
ΠΑΤΗΣΙΑ                              1.243071
ΓΚΥΖΗ                                0.923904
ΑΝΩ ΚΥΨΕΛΗ                           0.856711
ΚΟΛΩΝΟΣ                              0.848312
ΓΚΑΖΙ                                0.814715
ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ                       0.789518
ΠΕΔΙΟ ΑΡΕΩΣ                          0.755921
ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ                    0.722325
ΓΟΥΒΑ                                0.655132
ΒΟΤΑΝΙΚΟΣ                            0.621535
ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ                      0.621535
ΕΛΛΗΝΟΡΩΣΩΝ                          0.596338
ΑΝΩ ΠΑΤΗΣΙΑ                          0.512347
ΝΕΑ ΚΥΨΕΛΗ                           0.478750
1Ο ΝΕΚΡΟΤΑΦΕΙΟ                       0.445154
ΣΕΠΟΛΙΑ                              0.344364
ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ                     0.260373
ΠΟΛΥΓΩΝΟ                             0.218377
ΚΟΛΟΚΥΝΘΟΥ                           0.117588
ΠΡΟΜΠΟΝΑ                             0.092390
ΡΙΖΟΥΠΟΛΗ                            0.083991
ΡΗΓΙΛΛΗΣ                             0.033597
ΠΕΝΤΑΓΩΝΟ                            0.016798
Name: proportion, dtype: float64

 ### 4) Ποια είναι η μέση τιμή ενός διαμερίσματος ανά ημέρα όταν νοικιάζεται από χρήστη που διαθέτει κάτω  από 3 ακίνητα (ερασιτέχνης) και τρία ή περισσότερα ακίνητα? (σε όλη την Αθήνα και ανά περιοχή).

In [55]:
amateur_hosts = price_per_night['median'][0]
prof_hosts = price_per_night['median'][1]

precentage_difference=((prof_hosts-amateur_hosts)/((prof_hosts+amateur_hosts)/2))*100

text= f'Η μέση τιμή του διαμερίσματος ανά μέρα για τους οικοδεσπότες με 3 και πάνω ακίνητα είναι {prof_hosts} \
και για όσους έχουν έχουν κάτω απο 3 είναι {amateur_hosts}. Οι τιμές αυτές έχουν διαφορά {round(precentage_difference)}%'
text

'Η μέση τιμή του διαμερίσματος ανά μέρα για τους οικοδεσπότες με 3 και πάνω ακίνητα είναι 73.0 και για όσους έχουν έχουν κάτω απο 3 είναι 60.0. Οι τιμές αυτές έχουν διαφορά 20%'

In [56]:
text=f'Για κάθε περιοχή ξεχωριστά:'
text
pay_comp

many_properties,neighbourhood_cleansed,less_than_3,more_than_3,price_difference,percentage_difference
0,ΠΟΛΥΓΩΝΟ,55.0,134.0,79.0,83.597884
1,1Ο ΝΕΚΡΟΤΑΦΕΙΟ,49.0,93.0,44.0,61.971831
4,ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ,40.0,73.0,33.0,58.407080
3,ΡΙΖΟΥΠΟΛΗ,59.0,100.0,41.0,51.572327
2,ΖΑΠΠΕΙΟ,76.0,118.5,42.5,43.701799
6,ΠΕΔΙΟ ΑΡΕΩΣ,50.0,72.0,22.0,36.065574
5,ΑΚΡΟΠΟΛΗ,78.5,109.0,30.5,32.533333
10,ΕΛΛΗΝΟΡΩΣΩΝ,53.5,70.0,16.5,26.720648
7,ΚΟΥΚΑΚΙ-ΜΑΚΡΥΓΙΑΝΝΗ,74.0,96.0,22.0,25.882353
11,ΠΑΓΚΡΑΤΙ,57.0,73.0,16.0,24.615385
9,ΚΕΡΑΜΕΙΚΟΣ,69.0,87.0,18.0,23.076923
16,ΑΓΙΟΣ ΝΙΚΟΛΑΟΣ,40.0,50.0,10.0,22.222222
8,ΚΟΛΩΝΑΚΙ,84.0,104.0,20.0,21.276596
13,ΜΟΥΣΕΙΟ-ΕΞΑΡΧΕΙΑ-ΝΕΑΠΟΛΗ,56.0,69.0,13.0,20.800000
12,ΙΛΙΣΙΑ,65.0,80.0,15.0,20.689655
15,ΚΥΨΕΛΗ,50.0,61.5,11.5,20.627803
17,ΣΕΠΟΛΙΑ,50.0,60.0,10.0,18.181818
14,ΣΤΑΔΙΟ,65.0,77.0,12.0,16.901408
19,ΠΛΑΤΕΙΑ ΑΤΤΙΚΗΣ,45.0,51.0,6.0,12.500000
18,ΘΗΣΕΙΟ,70.5,79.0,8.5,11.371237
21,ΚΟΛΟΚΥΝΘΟΥ,40.0,44.5,4.5,10.650888
20,ΝΕΟΣ ΚΟΣΜΟΣ,60.0,66.0,6.0,9.523810
24,ΝΙΡΒΑΝΑ,41.0,45.0,4.0,9.302326
25,ΣΤΑΘΜΟΣ ΛΑΡΙΣΗΣ,48.0,52.0,4.0,8.000000
23,ΑΜΠΕΛΟΚΗΠΟΙ,55.0,59.0,4.0,7.017544
22,ΠΕΤΡΑΛΩΝΑ,58.0,62.0,4.0,6.666667
26,ΓΟΥΔΙ,57.5,60.0,2.5,4.255319
27,ΒΟΤΑΝΙΚΟΣ,58.0,60.0,2.0,3.389831
28,ΠΡΟΜΠΟΝΑ,60.0,61.5,1.5,2.469136
29,ΕΜΠΟΡΙΚΟ ΤΡΙΓΩΝΟ-ΠΛΑΚΑ,88.0,89.0,1.0,1.129944
30,ΛΥΚΑΒΗΤΤΟΣ,65.0,65.5,0.5,0.766284
33,ΓΟΥΒΑ,60.0,60.0,0.0,0.000000
31,ΚΟΛΩΝΟΣ,50.0,50.0,0.0,0.000000
32,ΠΑΤΗΣΙΑ,48.0,48.0,0.0,0.000000
34,ΑΚΑΔΗΜΙΑ ΠΛΑΤΩΝΟΣ,47.0,46.0,-1.0,-2.150538
35,ΑΝΩ ΠΑΤΗΣΙΑ,49.0,47.5,-1.5,-3.108808
36,ΑΝΩ ΚΥΨΕΛΗ,45.0,43.0,-2.0,-4.545455
37,ΠΛΑΤΕΙΑ ΑΜΕΡΙΚΗΣ,45.0,43.0,-2.0,-4.545455
38,ΓΚΑΖΙ,65.0,60.5,-4.5,-7.171315
39,ΑΓΙΟΣ ΚΩΝΣΤΑΝΤΙΝΟΣ-ΠΛΑΤΕΙΑ ΒΑΘΗΣ,51.0,46.0,-5.0,-10.309278
40,ΝΕΑ ΚΥΨΕΛΗ,56.5,50.0,-6.5,-12.206573
41,ΓΚΥΖΗ,51.0,40.0,-11.0,-24.175824
42,ΠΕΝΤΑΓΩΝΟ,43.5,NaN,NaN,NaN
43,ΡΗΓΙΛΛΗΣ,139.0,NaN,NaN,NaN

### 5) Ποιές είναι οι 5 περιοχές με τη μεγαλύτερη διαφορά μεταξύ αυτών των δύο τιμών. Σε πόσες περιοχές τα διαμερίσματα είναι πιο ακριβά;

In [57]:
more_than_0= len(more)
less_than_0= len(less)

text= f'Σε {more_than_0} περιοχές της Αθήνας, τα διαμερίσματα που ανήκουν σε επαγγελματίες hosts είναι πιο ακριβά από \
ότι τα διαμερίσματα που ανήκουν σε ερασιτέχνες hosts που είναι ακριβότερα σε {less_than_0} περιοχές.'
text

'Σε 31 περιοχές της Αθήνας, τα διαμερίσματα που ανήκουν σε επαγγελματίες hosts είναι πιο ακριβά από ότι τα διαμερίσματα που ανήκουν σε ερασιτέχνες hosts που είναι ακριβότερα σε 8 περιοχές.'

In [58]:
areas_greatest_price_dif= ', '.join(pay_comp['neighbourhood_cleansed'].loc[:4].tolist())

text= f'Οι 5 γειτονιές με τη μεγαλύτερη διαφορά τιμών μεταξύ των επαγγελματιών host\
και των ερασιτεχνών είναι οι {areas_greatest_price_dif}'
text

'Οι 5 γειτονιές με τη μεγαλύτερη διαφορά τιμών μεταξύ των επαγγελματιών hostκαι των ερασιτεχνών είναι οι ΠΟΛΥΓΩΝΟ, 1Ο ΝΕΚΡΟΤΑΦΕΙΟ, ΑΓΙΟΣ ΕΛΕΥΘΕΡΙΟΣ'